(load "downloader.lisp")

(defun main()
  (let ((setting (make-setting-data)))
    (msg)
    (setf (setting-data-numstr setting) (get-num-str (read)))
    (format t "Please set download path~%")
    (setf (setting-data-rootdir setting) (get-and-create-rootdir (read-line) setting))
    (setf (setting-data-body setting) (get-body (setting-data-numstr setting)))
    (get-profile-and-scenario-images setting)
    (get-onpu-cards setting)
    (get-hitokoma setting)
    (get-petit-cards setting)
    (get-main-cards setting)
    t))

#+clisp (if (equal (main) t)
           (progn (format t "~%Downloads Completed!~%")))
