(load "downloader.lisp")

(defun main()
  (msg)
  (setNum (read))
  (setBody)
  (createRootDir)
  ;; (getProfileImgAndScenarioImg)
  ;; (getOnpuCard)
  ;; (getHitokoma)
  ;; (getPetitcard)
  (getMaincard) t)

(if (equal (main) t)
    (format t "~%Downloads Completed!~%"))
