(load "downloader.lisp")

(defun main()
  (msg)
  (set-num (read))
  (set-body)
  (create-rootdir)
  (get-profile-and-scenario-images)
  (get-onpu-cards)
  (get-hitokoma)
  (get-petit-cards)
  (get-main-cards) t)

(if (equal (main) t)
    (progn (format t "~%Downloads Completed!~%")))
